import type { Metadata } from "next";
import type { ReactNode } from "react";
import { MSWProvider } from "@/mocks/MSWProvider";
import { MobileContainer } from "@/shared/ui/MobileContainer";
import { Toaster } from "@/shared/ui/Toaster";
import { Providers } from "./providers";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="ko" className="h-full overflow-hidden antialiased">
      <body className="h-full overflow-hidden">
        <MobileContainer>
          <MSWProvider>
            <Providers>{children}</Providers>
          </MSWProvider>
        </MobileContainer>
        <Toaster />
      </body>
    </html>
  );
}
